name: "first workflow"
on: 
  push:
  pull_request:
    branches:
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "setup node js in VM"
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: run ESLint on APP
        run: npm run lint

      - name: run tests cases
        run: npm run test

      - name: make react build
        run: npm run build